// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "interval_normalizati.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic interval_normalizati::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic interval_normalizati::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<42> interval_normalizati::ap_ST_fsm_state1 = "1";
const sc_lv<42> interval_normalizati::ap_ST_fsm_state2 = "10";
const sc_lv<42> interval_normalizati::ap_ST_fsm_state3 = "100";
const sc_lv<42> interval_normalizati::ap_ST_fsm_state4 = "1000";
const sc_lv<42> interval_normalizati::ap_ST_fsm_state5 = "10000";
const sc_lv<42> interval_normalizati::ap_ST_fsm_state6 = "100000";
const sc_lv<42> interval_normalizati::ap_ST_fsm_state7 = "1000000";
const sc_lv<42> interval_normalizati::ap_ST_fsm_state8 = "10000000";
const sc_lv<42> interval_normalizati::ap_ST_fsm_state9 = "100000000";
const sc_lv<42> interval_normalizati::ap_ST_fsm_state10 = "1000000000";
const sc_lv<42> interval_normalizati::ap_ST_fsm_state11 = "10000000000";
const sc_lv<42> interval_normalizati::ap_ST_fsm_state12 = "100000000000";
const sc_lv<42> interval_normalizati::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<42> interval_normalizati::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<42> interval_normalizati::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<42> interval_normalizati::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<42> interval_normalizati::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<42> interval_normalizati::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<42> interval_normalizati::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<42> interval_normalizati::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<42> interval_normalizati::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<42> interval_normalizati::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<42> interval_normalizati::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<42> interval_normalizati::ap_ST_fsm_state24 = "100000000000000000000000";
const sc_lv<42> interval_normalizati::ap_ST_fsm_state25 = "1000000000000000000000000";
const sc_lv<42> interval_normalizati::ap_ST_fsm_state26 = "10000000000000000000000000";
const sc_lv<42> interval_normalizati::ap_ST_fsm_state27 = "100000000000000000000000000";
const sc_lv<42> interval_normalizati::ap_ST_fsm_state28 = "1000000000000000000000000000";
const sc_lv<42> interval_normalizati::ap_ST_fsm_state29 = "10000000000000000000000000000";
const sc_lv<42> interval_normalizati::ap_ST_fsm_state30 = "100000000000000000000000000000";
const sc_lv<42> interval_normalizati::ap_ST_fsm_state31 = "1000000000000000000000000000000";
const sc_lv<42> interval_normalizati::ap_ST_fsm_state32 = "10000000000000000000000000000000";
const sc_lv<42> interval_normalizati::ap_ST_fsm_state33 = "100000000000000000000000000000000";
const sc_lv<42> interval_normalizati::ap_ST_fsm_state34 = "1000000000000000000000000000000000";
const sc_lv<42> interval_normalizati::ap_ST_fsm_state35 = "10000000000000000000000000000000000";
const sc_lv<42> interval_normalizati::ap_ST_fsm_state36 = "100000000000000000000000000000000000";
const sc_lv<42> interval_normalizati::ap_ST_fsm_state37 = "1000000000000000000000000000000000000";
const sc_lv<42> interval_normalizati::ap_ST_fsm_state38 = "10000000000000000000000000000000000000";
const sc_lv<42> interval_normalizati::ap_ST_fsm_state39 = "100000000000000000000000000000000000000";
const sc_lv<42> interval_normalizati::ap_ST_fsm_state40 = "1000000000000000000000000000000000000000";
const sc_lv<42> interval_normalizati::ap_ST_fsm_state41 = "10000000000000000000000000000000000000000";
const sc_lv<42> interval_normalizati::ap_ST_fsm_state42 = "100000000000000000000000000000000000000000";
const sc_lv<32> interval_normalizati::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> interval_normalizati::ap_const_lv32_1 = "1";
const sc_lv<1> interval_normalizati::ap_const_lv1_1 = "1";
const sc_lv<32> interval_normalizati::ap_const_lv32_29 = "101001";
const sc_lv<32> interval_normalizati::ap_const_lv32_9 = "1001";
const sc_lv<32> interval_normalizati::ap_const_lv32_1D = "11101";
const sc_lv<32> interval_normalizati::ap_const_lv32_C = "1100";
const sc_lv<32> interval_normalizati::ap_const_lv32_24 = "100100";
const sc_lv<32> interval_normalizati::ap_const_lv32_21 = "100001";
const sc_lv<32> interval_normalizati::ap_const_lv32_28 = "101000";
const sc_lv<32> interval_normalizati::ap_const_lv32_2 = "10";
const sc_lv<32> interval_normalizati::ap_const_lv32_5 = "101";
const sc_lv<32> interval_normalizati::ap_const_lv32_6 = "110";
const sc_lv<1> interval_normalizati::ap_const_lv1_0 = "0";
const sc_lv<32> interval_normalizati::ap_const_lv32_18 = "11000";
const sc_lv<32> interval_normalizati::ap_const_lv32_19 = "11001";
const sc_lv<32> interval_normalizati::ap_const_lv32_1A = "11010";
const sc_lv<32> interval_normalizati::ap_const_lv32_1B = "11011";
const sc_lv<32> interval_normalizati::ap_const_lv32_1C = "11100";
const sc_lv<8> interval_normalizati::ap_const_lv8_0 = "00000000";
const sc_lv<10> interval_normalizati::ap_const_lv10_0 = "0000000000";
const sc_lv<32> interval_normalizati::ap_const_lv32_1E = "11110";
const sc_lv<32> interval_normalizati::ap_const_lv32_25 = "100101";
const sc_lv<32> interval_normalizati::ap_const_lv32_A = "1010";
const sc_lv<32> interval_normalizati::ap_const_lv32_22 = "100010";
const sc_lv<32> interval_normalizati::ap_const_lv32_43480000 = "1000011010010000000000000000000";
const sc_lv<32> interval_normalizati::ap_const_lv32_D = "1101";
const sc_lv<11> interval_normalizati::ap_const_lv11_200 = "1000000000";
const sc_lv<12> interval_normalizati::ap_const_lv12_FA = "11111010";
const sc_lv<8> interval_normalizati::ap_const_lv8_C8 = "11001000";
const sc_lv<8> interval_normalizati::ap_const_lv8_1 = "1";
const sc_lv<32> interval_normalizati::ap_const_lv32_1F = "11111";
const sc_lv<32> interval_normalizati::ap_const_lv32_17 = "10111";
const sc_lv<9> interval_normalizati::ap_const_lv9_181 = "110000001";
const sc_lv<32> interval_normalizati::ap_const_lv32_8 = "1000";
const sc_lv<8> interval_normalizati::ap_const_lv8_7F = "1111111";
const sc_lv<32> interval_normalizati::ap_const_lv32_37 = "110111";
const sc_lv<33> interval_normalizati::ap_const_lv33_200 = "1000000000";
const sc_lv<32> interval_normalizati::ap_const_lv32_20 = "100000";
const sc_lv<9> interval_normalizati::ap_const_lv9_0 = "000000000";
const sc_lv<23> interval_normalizati::ap_const_lv23_0 = "00000000000000000000000";
const sc_lv<2> interval_normalizati::ap_const_lv2_0 = "00";
const sc_lv<2> interval_normalizati::ap_const_lv2_1 = "1";
const bool interval_normalizati::ap_const_boolean_1 = true;

interval_normalizati::interval_normalizati(sc_module_name name) : sc_module(name), mVcdFile(0) {
    buf_buffer_U = new interval_normalizdEe("buf_buffer_U");
    buf_buffer_U->clk(ap_clk);
    buf_buffer_U->reset(ap_rst);
    buf_buffer_U->address0(buf_buffer_address0);
    buf_buffer_U->ce0(buf_buffer_ce0);
    buf_buffer_U->q0(buf_buffer_q0);
    buf_buffer_U->address1(buf_buffer_address1);
    buf_buffer_U->ce1(buf_buffer_ce1);
    buf_buffer_U->q1(buf_buffer_q1);
    feature_extractoreOg_U7 = new feature_extractoreOg<1,4,32,32,32>("feature_extractoreOg_U7");
    feature_extractoreOg_U7->clk(ap_clk);
    feature_extractoreOg_U7->reset(ap_rst);
    feature_extractoreOg_U7->din0(grp_fu_175_p0);
    feature_extractoreOg_U7->din1(grp_fu_175_p1);
    feature_extractoreOg_U7->opcode(grp_fu_175_opcode);
    feature_extractoreOg_U7->ce(ap_var_for_const0);
    feature_extractoreOg_U7->dout(grp_fu_175_p2);
    feature_extractorfYi_U8 = new feature_extractorfYi<1,4,32,32,32>("feature_extractorfYi_U8");
    feature_extractorfYi_U8->clk(ap_clk);
    feature_extractorfYi_U8->reset(ap_rst);
    feature_extractorfYi_U8->din0(pos_reg_643);
    feature_extractorfYi_U8->din1(reg_195);
    feature_extractorfYi_U8->ce(ap_var_for_const0);
    feature_extractorfYi_U8->dout(grp_fu_179_p2);
    feature_extractorg8j_U9 = new feature_extractorg8j<1,3,32,32,32>("feature_extractorg8j_U9");
    feature_extractorg8j_U9->clk(ap_clk);
    feature_extractorg8j_U9->reset(ap_rst);
    feature_extractorg8j_U9->din0(grp_fu_183_p0);
    feature_extractorg8j_U9->din1(grp_fu_183_p1);
    feature_extractorg8j_U9->ce(ap_var_for_const0);
    feature_extractorg8j_U9->dout(grp_fu_183_p2);
    feature_extractorhbi_U10 = new feature_extractorhbi<1,12,32,32,32>("feature_extractorhbi_U10");
    feature_extractorhbi_U10->clk(ap_clk);
    feature_extractorhbi_U10->reset(ap_rst);
    feature_extractorhbi_U10->din0(reg_201);
    feature_extractorhbi_U10->din1(ap_var_for_const1);
    feature_extractorhbi_U10->ce(ap_var_for_const0);
    feature_extractorhbi_U10->dout(grp_fu_187_p2);
    feature_extractoribs_U11 = new feature_extractoribs<1,4,32,32>("feature_extractoribs_U11");
    feature_extractoribs_U11->clk(ap_clk);
    feature_extractoribs_U11->reset(ap_rst);
    feature_extractoribs_U11->din0(grp_fu_192_p0);
    feature_extractoribs_U11->ce(ap_var_for_const0);
    feature_extractoribs_U11->dout(grp_fu_192_p1);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln339_fu_350_p2);
    sensitive << ( zext_ln339_fu_346_p1 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state25);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state26);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state27);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state28);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state29);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state30);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state31);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state34);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state35);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state37);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state38);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state41);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state42);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state2);
    sensitive << ( peaks_V_V_empty_n );
    sensitive << ( tmp_nbreadreq_fu_120_p3 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( peaks_V_V_empty_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_nbreadreq_fu_120_p3 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( real_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( internal_ap_ready );

    SC_METHOD(thread_buf_buffer_address0);
    sensitive << ( ap_CS_fsm_state29 );
    sensitive << ( sext_ln544_fu_543_p1 );

    SC_METHOD(thread_buf_buffer_address1);
    sensitive << ( ap_CS_fsm_state29 );
    sensitive << ( sext_ln544_1_fu_581_p1 );

    SC_METHOD(thread_buf_buffer_ce0);
    sensitive << ( ap_CS_fsm_state29 );

    SC_METHOD(thread_buf_buffer_ce1);
    sensitive << ( ap_CS_fsm_state29 );

    SC_METHOD(thread_grp_fu_175_opcode);
    sensitive << ( ap_CS_fsm_state31 );
    sensitive << ( ap_CS_fsm_state38 );

    SC_METHOD(thread_grp_fu_175_p0);
    sensitive << ( v0_reg_701 );
    sensitive << ( v1_reg_707 );
    sensitive << ( ap_CS_fsm_state31 );
    sensitive << ( ap_CS_fsm_state38 );

    SC_METHOD(thread_grp_fu_175_p1);
    sensitive << ( reg_201 );
    sensitive << ( v0_reg_701 );
    sensitive << ( ap_CS_fsm_state31 );
    sensitive << ( ap_CS_fsm_state38 );

    SC_METHOD(thread_grp_fu_183_p0);
    sensitive << ( reg_207 );
    sensitive << ( tmp_8_reg_620 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state35 );

    SC_METHOD(thread_grp_fu_183_p1);
    sensitive << ( reg_195 );
    sensitive << ( tmp_4_reg_712 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state35 );

    SC_METHOD(thread_grp_fu_192_p0);
    sensitive << ( sext_ln86_fu_279_p1 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( zext_ln85_fu_286_p1 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( p_Val2_6_reg_649 );
    sensitive << ( ap_CS_fsm_state27 );

    SC_METHOD(thread_i_fu_297_p2);
    sensitive << ( i_0_reg_164 );

    SC_METHOD(thread_icmp_ln79_fu_273_p2);
    sensitive << ( peaks_V_V_empty_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_nbreadreq_fu_120_p3 );
    sensitive << ( select_ln895_fu_265_p3 );

    SC_METHOD(thread_icmp_ln85_fu_291_p2);
    sensitive << ( icmp_ln79_reg_611 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( i_0_reg_164 );

    SC_METHOD(thread_icmp_ln895_fu_221_p2);
    sensitive << ( peaks_V_V_dout );
    sensitive << ( peaks_V_V_empty_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_nbreadreq_fu_120_p3 );
    sensitive << ( tmp_V_fu_112 );

    SC_METHOD(thread_idx_0_fu_450_p2);
    sensitive << ( zext_ln87_reg_625 );
    sensitive << ( p_Val2_6_reg_649 );

    SC_METHOD(thread_idx_1_fu_454_p2);
    sensitive << ( idx_0_reg_655 );

    SC_METHOD(thread_internal_ap_ready);
    sensitive << ( peaks_V_V_empty_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_nbreadreq_fu_120_p3 );

    SC_METHOD(thread_interval_len_fu_259_p2);
    sensitive << ( sext_ln75_fu_255_p1 );
    sensitive << ( zext_ln75_fu_245_p1 );

    SC_METHOD(thread_isNeg_fu_356_p3);
    sensitive << ( add_ln339_fu_350_p2 );

    SC_METHOD(thread_lhs_V_fu_227_p1);
    sensitive << ( peaks_V_V_dout );

    SC_METHOD(thread_mantissa_V_fu_332_p4);
    sensitive << ( tmp_V_8_fu_328_p1 );

    SC_METHOD(thread_normalized_out_V_blk_n);
    sensitive << ( normalized_out_V_full_n );
    sensitive << ( ap_CS_fsm_state42 );

    SC_METHOD(thread_normalized_out_V_din);
    sensitive << ( normalized_out_V_full_n );
    sensitive << ( ap_CS_fsm_state42 );
    sensitive << ( reg_207 );

    SC_METHOD(thread_normalized_out_V_write);
    sensitive << ( normalized_out_V_full_n );
    sensitive << ( ap_CS_fsm_state42 );

    SC_METHOD(thread_p_Result_s_fu_310_p3);
    sensitive << ( p_Val2_s_fu_307_p1 );

    SC_METHOD(thread_p_Val2_5_fu_428_p3);
    sensitive << ( isNeg_fu_356_p3 );
    sensitive << ( zext_ln662_fu_414_p1 );
    sensitive << ( tmp_2_fu_418_p4 );

    SC_METHOD(thread_p_Val2_6_fu_442_p3);
    sensitive << ( p_Val2_5_fu_428_p3 );
    sensitive << ( p_Result_s_fu_310_p3 );
    sensitive << ( result_V_1_fu_436_p2 );

    SC_METHOD(thread_p_Val2_s_fu_307_p1);
    sensitive << ( pos_reg_643 );

    SC_METHOD(thread_peaks_V_V_blk_n);
    sensitive << ( peaks_V_V_empty_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_nbreadreq_fu_120_p3 );

    SC_METHOD(thread_peaks_V_V_read);
    sensitive << ( peaks_V_V_empty_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_nbreadreq_fu_120_p3 );

    SC_METHOD(thread_r_V_1_fu_400_p2);
    sensitive << ( zext_ln682_fu_342_p1 );
    sensitive << ( zext_ln1287_fu_390_p1 );

    SC_METHOD(thread_r_V_fu_394_p2);
    sensitive << ( mantissa_V_fu_332_p4 );
    sensitive << ( sext_ln1311_2_fu_386_p1 );

    SC_METHOD(thread_real_start);
    sensitive << ( ap_start );
    sensitive << ( start_full_n );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_result_V_1_fu_436_p2);
    sensitive << ( p_Val2_5_fu_428_p3 );

    SC_METHOD(thread_ret_V_4_fu_462_p2);
    sensitive << ( rhs_V_1_fu_459_p1 );

    SC_METHOD(thread_ret_V_5_fu_536_p3);
    sensitive << ( tmp_14_reg_661 );
    sensitive << ( sub_ln1372_2_fu_523_p2 );
    sensitive << ( tmp_6_fu_529_p3 );

    SC_METHOD(thread_ret_V_6_fu_488_p2);
    sensitive << ( rhs_V_2_fu_484_p1 );

    SC_METHOD(thread_ret_V_7_fu_574_p3);
    sensitive << ( tmp_16_reg_676 );
    sensitive << ( sub_ln1372_4_fu_561_p2 );
    sensitive << ( tmp_7_fu_567_p3 );

    SC_METHOD(thread_ret_V_fu_235_p2);
    sensitive << ( lhs_V_fu_227_p1 );
    sensitive << ( rhs_V_fu_231_p1 );

    SC_METHOD(thread_rhs_V_1_fu_459_p1);
    sensitive << ( idx_0_reg_655 );

    SC_METHOD(thread_rhs_V_2_fu_484_p1);
    sensitive << ( idx_1_fu_454_p2 );

    SC_METHOD(thread_rhs_V_fu_231_p1);
    sensitive << ( tmp_V_fu_112 );

    SC_METHOD(thread_select_ln895_fu_265_p3);
    sensitive << ( icmp_ln895_fu_221_p2 );
    sensitive << ( sext_ln71_fu_241_p1 );
    sensitive << ( interval_len_fu_259_p2 );

    SC_METHOD(thread_sext_ln1311_1_fu_382_p1);
    sensitive << ( ush_fu_374_p3 );

    SC_METHOD(thread_sext_ln1311_2_fu_386_p1);
    sensitive << ( ush_fu_374_p3 );

    SC_METHOD(thread_sext_ln1311_fu_370_p1);
    sensitive << ( sub_ln1311_fu_364_p2 );

    SC_METHOD(thread_sext_ln544_1_fu_581_p1);
    sensitive << ( ret_V_7_fu_574_p3 );

    SC_METHOD(thread_sext_ln544_fu_543_p1);
    sensitive << ( ret_V_5_fu_536_p3 );

    SC_METHOD(thread_sext_ln71_fu_241_p1);
    sensitive << ( ret_V_fu_235_p2 );

    SC_METHOD(thread_sext_ln75_fu_255_p1);
    sensitive << ( sub_ln75_fu_249_p2 );

    SC_METHOD(thread_sext_ln86_fu_279_p1);
    sensitive << ( select_ln895_reg_606 );

    SC_METHOD(thread_start_out);
    sensitive << ( real_start );

    SC_METHOD(thread_start_write);
    sensitive << ( real_start );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_sub_ln1311_fu_364_p2);
    sensitive << ( tmp_V_7_fu_318_p4 );

    SC_METHOD(thread_sub_ln1372_2_fu_523_p2);
    sensitive << ( tmp_15_fu_515_p3 );

    SC_METHOD(thread_sub_ln1372_3_fu_548_p2);
    sensitive << ( trunc_ln1372_4_reg_686 );

    SC_METHOD(thread_sub_ln1372_4_fu_561_p2);
    sensitive << ( tmp_17_fu_553_p3 );

    SC_METHOD(thread_sub_ln1372_fu_510_p2);
    sensitive << ( trunc_ln1372_2_reg_671 );

    SC_METHOD(thread_sub_ln75_fu_249_p2);
    sensitive << ( rhs_V_fu_231_p1 );

    SC_METHOD(thread_tmp_13_fu_406_p3);
    sensitive << ( r_V_fu_394_p2 );

    SC_METHOD(thread_tmp_15_fu_515_p3);
    sensitive << ( sub_ln1372_fu_510_p2 );

    SC_METHOD(thread_tmp_17_fu_553_p3);
    sensitive << ( sub_ln1372_3_fu_548_p2 );

    SC_METHOD(thread_tmp_2_fu_418_p4);
    sensitive << ( r_V_1_fu_400_p2 );

    SC_METHOD(thread_tmp_6_fu_529_p3);
    sensitive << ( trunc_ln1372_reg_666 );

    SC_METHOD(thread_tmp_7_fu_567_p3);
    sensitive << ( trunc_ln1372_3_reg_681 );

    SC_METHOD(thread_tmp_V_7_fu_318_p4);
    sensitive << ( p_Val2_s_fu_307_p1 );

    SC_METHOD(thread_tmp_V_8_fu_328_p1);
    sensitive << ( p_Val2_s_fu_307_p1 );

    SC_METHOD(thread_tmp_nbreadreq_fu_120_p3);
    sensitive << ( peaks_V_V_empty_n );

    SC_METHOD(thread_trunc_ln1372_2_fu_480_p1);
    sensitive << ( ret_V_4_fu_462_p2 );

    SC_METHOD(thread_trunc_ln1372_3_fu_502_p1);
    sensitive << ( ret_V_6_fu_488_p2 );

    SC_METHOD(thread_trunc_ln1372_4_fu_506_p1);
    sensitive << ( ret_V_6_fu_488_p2 );

    SC_METHOD(thread_trunc_ln1372_fu_476_p1);
    sensitive << ( ret_V_4_fu_462_p2 );

    SC_METHOD(thread_ush_fu_374_p3);
    sensitive << ( add_ln339_fu_350_p2 );
    sensitive << ( isNeg_fu_356_p3 );
    sensitive << ( sext_ln1311_fu_370_p1 );

    SC_METHOD(thread_zext_ln1287_fu_390_p1);
    sensitive << ( sext_ln1311_1_fu_382_p1 );

    SC_METHOD(thread_zext_ln339_fu_346_p1);
    sensitive << ( tmp_V_7_fu_318_p4 );

    SC_METHOD(thread_zext_ln662_fu_414_p1);
    sensitive << ( tmp_13_fu_406_p3 );

    SC_METHOD(thread_zext_ln682_fu_342_p1);
    sensitive << ( mantissa_V_fu_332_p4 );

    SC_METHOD(thread_zext_ln75_fu_245_p1);
    sensitive << ( peaks_V_V_dout );

    SC_METHOD(thread_zext_ln85_fu_286_p1);
    sensitive << ( i_0_reg_164 );

    SC_METHOD(thread_zext_ln87_fu_283_p1);
    sensitive << ( tmp_V_load_reg_596 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( peaks_V_V_empty_n );
    sensitive << ( normalized_out_V_full_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_nbreadreq_fu_120_p3 );
    sensitive << ( ap_CS_fsm_state42 );
    sensitive << ( icmp_ln79_fu_273_p2 );
    sensitive << ( icmp_ln79_reg_611 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln85_fu_291_p2 );

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const1);

    start_once_reg = SC_LOGIC_0;
    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "000000000000000000000000000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "interval_normalizati_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, start_full_n, "(port)start_full_n");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, start_out, "(port)start_out");
    sc_trace(mVcdFile, start_write, "(port)start_write");
    sc_trace(mVcdFile, peaks_V_V_dout, "(port)peaks_V_V_dout");
    sc_trace(mVcdFile, peaks_V_V_empty_n, "(port)peaks_V_V_empty_n");
    sc_trace(mVcdFile, peaks_V_V_read, "(port)peaks_V_V_read");
    sc_trace(mVcdFile, normalized_out_V_din, "(port)normalized_out_V_din");
    sc_trace(mVcdFile, normalized_out_V_full_n, "(port)normalized_out_V_full_n");
    sc_trace(mVcdFile, normalized_out_V_write, "(port)normalized_out_V_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, real_start, "real_start");
    sc_trace(mVcdFile, start_once_reg, "start_once_reg");
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, internal_ap_ready, "internal_ap_ready");
    sc_trace(mVcdFile, peaks_V_V_blk_n, "peaks_V_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, tmp_nbreadreq_fu_120_p3, "tmp_nbreadreq_fu_120_p3");
    sc_trace(mVcdFile, normalized_out_V_blk_n, "normalized_out_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state42, "ap_CS_fsm_state42");
    sc_trace(mVcdFile, grp_fu_192_p1, "grp_fu_192_p1");
    sc_trace(mVcdFile, reg_195, "reg_195");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, ap_CS_fsm_state30, "ap_CS_fsm_state30");
    sc_trace(mVcdFile, grp_fu_183_p2, "grp_fu_183_p2");
    sc_trace(mVcdFile, reg_201, "reg_201");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, ap_CS_fsm_state37, "ap_CS_fsm_state37");
    sc_trace(mVcdFile, grp_fu_175_p2, "grp_fu_175_p2");
    sc_trace(mVcdFile, reg_207, "reg_207");
    sc_trace(mVcdFile, ap_CS_fsm_state34, "ap_CS_fsm_state34");
    sc_trace(mVcdFile, ap_CS_fsm_state41, "ap_CS_fsm_state41");
    sc_trace(mVcdFile, tmp_V_load_reg_596, "tmp_V_load_reg_596");
    sc_trace(mVcdFile, ap_block_state2, "ap_block_state2");
    sc_trace(mVcdFile, tmp_V_6_reg_601, "tmp_V_6_reg_601");
    sc_trace(mVcdFile, select_ln895_fu_265_p3, "select_ln895_fu_265_p3");
    sc_trace(mVcdFile, select_ln895_reg_606, "select_ln895_reg_606");
    sc_trace(mVcdFile, icmp_ln79_fu_273_p2, "icmp_ln79_fu_273_p2");
    sc_trace(mVcdFile, icmp_ln79_reg_611, "icmp_ln79_reg_611");
    sc_trace(mVcdFile, sext_ln86_fu_279_p1, "sext_ln86_fu_279_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, tmp_8_reg_620, "tmp_8_reg_620");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, zext_ln87_fu_283_p1, "zext_ln87_fu_283_p1");
    sc_trace(mVcdFile, zext_ln87_reg_625, "zext_ln87_reg_625");
    sc_trace(mVcdFile, zext_ln85_fu_286_p1, "zext_ln85_fu_286_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, i_fu_297_p2, "i_fu_297_p2");
    sc_trace(mVcdFile, i_reg_638, "i_reg_638");
    sc_trace(mVcdFile, grp_fu_187_p2, "grp_fu_187_p2");
    sc_trace(mVcdFile, pos_reg_643, "pos_reg_643");
    sc_trace(mVcdFile, ap_CS_fsm_state25, "ap_CS_fsm_state25");
    sc_trace(mVcdFile, p_Val2_6_fu_442_p3, "p_Val2_6_fu_442_p3");
    sc_trace(mVcdFile, p_Val2_6_reg_649, "p_Val2_6_reg_649");
    sc_trace(mVcdFile, ap_CS_fsm_state26, "ap_CS_fsm_state26");
    sc_trace(mVcdFile, idx_0_fu_450_p2, "idx_0_fu_450_p2");
    sc_trace(mVcdFile, idx_0_reg_655, "idx_0_reg_655");
    sc_trace(mVcdFile, ap_CS_fsm_state27, "ap_CS_fsm_state27");
    sc_trace(mVcdFile, tmp_14_reg_661, "tmp_14_reg_661");
    sc_trace(mVcdFile, ap_CS_fsm_state28, "ap_CS_fsm_state28");
    sc_trace(mVcdFile, trunc_ln1372_fu_476_p1, "trunc_ln1372_fu_476_p1");
    sc_trace(mVcdFile, trunc_ln1372_reg_666, "trunc_ln1372_reg_666");
    sc_trace(mVcdFile, trunc_ln1372_2_fu_480_p1, "trunc_ln1372_2_fu_480_p1");
    sc_trace(mVcdFile, trunc_ln1372_2_reg_671, "trunc_ln1372_2_reg_671");
    sc_trace(mVcdFile, tmp_16_reg_676, "tmp_16_reg_676");
    sc_trace(mVcdFile, trunc_ln1372_3_fu_502_p1, "trunc_ln1372_3_fu_502_p1");
    sc_trace(mVcdFile, trunc_ln1372_3_reg_681, "trunc_ln1372_3_reg_681");
    sc_trace(mVcdFile, trunc_ln1372_4_fu_506_p1, "trunc_ln1372_4_fu_506_p1");
    sc_trace(mVcdFile, trunc_ln1372_4_reg_686, "trunc_ln1372_4_reg_686");
    sc_trace(mVcdFile, ap_CS_fsm_state29, "ap_CS_fsm_state29");
    sc_trace(mVcdFile, buf_buffer_q0, "buf_buffer_q0");
    sc_trace(mVcdFile, v0_reg_701, "v0_reg_701");
    sc_trace(mVcdFile, buf_buffer_q1, "buf_buffer_q1");
    sc_trace(mVcdFile, v1_reg_707, "v1_reg_707");
    sc_trace(mVcdFile, grp_fu_179_p2, "grp_fu_179_p2");
    sc_trace(mVcdFile, tmp_4_reg_712, "tmp_4_reg_712");
    sc_trace(mVcdFile, buf_buffer_address0, "buf_buffer_address0");
    sc_trace(mVcdFile, buf_buffer_ce0, "buf_buffer_ce0");
    sc_trace(mVcdFile, buf_buffer_address1, "buf_buffer_address1");
    sc_trace(mVcdFile, buf_buffer_ce1, "buf_buffer_ce1");
    sc_trace(mVcdFile, i_0_reg_164, "i_0_reg_164");
    sc_trace(mVcdFile, sext_ln544_fu_543_p1, "sext_ln544_fu_543_p1");
    sc_trace(mVcdFile, sext_ln544_1_fu_581_p1, "sext_ln544_1_fu_581_p1");
    sc_trace(mVcdFile, tmp_V_fu_112, "tmp_V_fu_112");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, icmp_ln85_fu_291_p2, "icmp_ln85_fu_291_p2");
    sc_trace(mVcdFile, grp_fu_175_p0, "grp_fu_175_p0");
    sc_trace(mVcdFile, grp_fu_175_p1, "grp_fu_175_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state31, "ap_CS_fsm_state31");
    sc_trace(mVcdFile, ap_CS_fsm_state38, "ap_CS_fsm_state38");
    sc_trace(mVcdFile, grp_fu_183_p0, "grp_fu_183_p0");
    sc_trace(mVcdFile, grp_fu_183_p1, "grp_fu_183_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, ap_CS_fsm_state35, "ap_CS_fsm_state35");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, grp_fu_192_p0, "grp_fu_192_p0");
    sc_trace(mVcdFile, lhs_V_fu_227_p1, "lhs_V_fu_227_p1");
    sc_trace(mVcdFile, rhs_V_fu_231_p1, "rhs_V_fu_231_p1");
    sc_trace(mVcdFile, ret_V_fu_235_p2, "ret_V_fu_235_p2");
    sc_trace(mVcdFile, sub_ln75_fu_249_p2, "sub_ln75_fu_249_p2");
    sc_trace(mVcdFile, sext_ln75_fu_255_p1, "sext_ln75_fu_255_p1");
    sc_trace(mVcdFile, zext_ln75_fu_245_p1, "zext_ln75_fu_245_p1");
    sc_trace(mVcdFile, icmp_ln895_fu_221_p2, "icmp_ln895_fu_221_p2");
    sc_trace(mVcdFile, sext_ln71_fu_241_p1, "sext_ln71_fu_241_p1");
    sc_trace(mVcdFile, interval_len_fu_259_p2, "interval_len_fu_259_p2");
    sc_trace(mVcdFile, p_Val2_s_fu_307_p1, "p_Val2_s_fu_307_p1");
    sc_trace(mVcdFile, tmp_V_8_fu_328_p1, "tmp_V_8_fu_328_p1");
    sc_trace(mVcdFile, mantissa_V_fu_332_p4, "mantissa_V_fu_332_p4");
    sc_trace(mVcdFile, tmp_V_7_fu_318_p4, "tmp_V_7_fu_318_p4");
    sc_trace(mVcdFile, zext_ln339_fu_346_p1, "zext_ln339_fu_346_p1");
    sc_trace(mVcdFile, add_ln339_fu_350_p2, "add_ln339_fu_350_p2");
    sc_trace(mVcdFile, sub_ln1311_fu_364_p2, "sub_ln1311_fu_364_p2");
    sc_trace(mVcdFile, isNeg_fu_356_p3, "isNeg_fu_356_p3");
    sc_trace(mVcdFile, sext_ln1311_fu_370_p1, "sext_ln1311_fu_370_p1");
    sc_trace(mVcdFile, ush_fu_374_p3, "ush_fu_374_p3");
    sc_trace(mVcdFile, sext_ln1311_1_fu_382_p1, "sext_ln1311_1_fu_382_p1");
    sc_trace(mVcdFile, sext_ln1311_2_fu_386_p1, "sext_ln1311_2_fu_386_p1");
    sc_trace(mVcdFile, zext_ln682_fu_342_p1, "zext_ln682_fu_342_p1");
    sc_trace(mVcdFile, zext_ln1287_fu_390_p1, "zext_ln1287_fu_390_p1");
    sc_trace(mVcdFile, r_V_fu_394_p2, "r_V_fu_394_p2");
    sc_trace(mVcdFile, tmp_13_fu_406_p3, "tmp_13_fu_406_p3");
    sc_trace(mVcdFile, r_V_1_fu_400_p2, "r_V_1_fu_400_p2");
    sc_trace(mVcdFile, zext_ln662_fu_414_p1, "zext_ln662_fu_414_p1");
    sc_trace(mVcdFile, tmp_2_fu_418_p4, "tmp_2_fu_418_p4");
    sc_trace(mVcdFile, p_Val2_5_fu_428_p3, "p_Val2_5_fu_428_p3");
    sc_trace(mVcdFile, p_Result_s_fu_310_p3, "p_Result_s_fu_310_p3");
    sc_trace(mVcdFile, result_V_1_fu_436_p2, "result_V_1_fu_436_p2");
    sc_trace(mVcdFile, rhs_V_1_fu_459_p1, "rhs_V_1_fu_459_p1");
    sc_trace(mVcdFile, ret_V_4_fu_462_p2, "ret_V_4_fu_462_p2");
    sc_trace(mVcdFile, idx_1_fu_454_p2, "idx_1_fu_454_p2");
    sc_trace(mVcdFile, rhs_V_2_fu_484_p1, "rhs_V_2_fu_484_p1");
    sc_trace(mVcdFile, ret_V_6_fu_488_p2, "ret_V_6_fu_488_p2");
    sc_trace(mVcdFile, sub_ln1372_fu_510_p2, "sub_ln1372_fu_510_p2");
    sc_trace(mVcdFile, tmp_15_fu_515_p3, "tmp_15_fu_515_p3");
    sc_trace(mVcdFile, sub_ln1372_2_fu_523_p2, "sub_ln1372_2_fu_523_p2");
    sc_trace(mVcdFile, tmp_6_fu_529_p3, "tmp_6_fu_529_p3");
    sc_trace(mVcdFile, ret_V_5_fu_536_p3, "ret_V_5_fu_536_p3");
    sc_trace(mVcdFile, sub_ln1372_3_fu_548_p2, "sub_ln1372_3_fu_548_p2");
    sc_trace(mVcdFile, tmp_17_fu_553_p3, "tmp_17_fu_553_p3");
    sc_trace(mVcdFile, sub_ln1372_4_fu_561_p2, "sub_ln1372_4_fu_561_p2");
    sc_trace(mVcdFile, tmp_7_fu_567_p3, "tmp_7_fu_567_p3");
    sc_trace(mVcdFile, ret_V_7_fu_574_p3, "ret_V_7_fu_574_p3");
    sc_trace(mVcdFile, grp_fu_175_opcode, "grp_fu_175_opcode");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

interval_normalizati::~interval_normalizati() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete buf_buffer_U;
    delete feature_extractoreOg_U7;
    delete feature_extractorfYi_U8;
    delete feature_extractorg8j_U9;
    delete feature_extractorhbi_U10;
    delete feature_extractoribs_U11;
}

void interval_normalizati::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void interval_normalizati::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv32_43480000;
}

void interval_normalizati::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    !(esl_seteq<1,1,1>(tmp_nbreadreq_fu_120_p3.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, peaks_V_V_empty_n.read())) && 
                    esl_seteq<1,1,1>(tmp_nbreadreq_fu_120_p3.read(), ap_const_lv1_0))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        i_0_reg_164 = ap_const_lv8_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state42.read()) && 
                esl_seteq<1,1,1>(normalized_out_V_full_n.read(), ap_const_logic_1))) {
        i_0_reg_164 = i_reg_638.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        start_once_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_0, internal_ap_ready.read()))) {
            start_once_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, internal_ap_ready.read())) {
            start_once_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(icmp_ln79_reg_611.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln85_fu_291_p2.read()))) {
        tmp_V_fu_112 = tmp_V_6_reg_601.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        tmp_V_fu_112 = ap_const_lv10_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(icmp_ln79_reg_611.read(), ap_const_lv1_0))) {
        i_reg_638 = i_fu_297_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(tmp_nbreadreq_fu_120_p3.read(), ap_const_lv1_1) && !(esl_seteq<1,1,1>(tmp_nbreadreq_fu_120_p3.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, peaks_V_V_empty_n.read())))) {
        icmp_ln79_reg_611 = icmp_ln79_fu_273_p2.read();
        select_ln895_reg_606 = select_ln895_fu_265_p3.read();
        tmp_V_6_reg_601 = peaks_V_V_dout.read();
        tmp_V_load_reg_596 = tmp_V_fu_112.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state27.read())) {
        idx_0_reg_655 = idx_0_fu_450_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read())) {
        p_Val2_6_reg_649 = p_Val2_6_fu_442_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state25.read())) {
        pos_reg_643 = grp_fu_187_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state30.read()))) {
        reg_195 = grp_fu_192_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state37.read()))) {
        reg_201 = grp_fu_183_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state34.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state41.read()))) {
        reg_207 = grp_fu_175_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state28.read())) {
        tmp_14_reg_661 = ret_V_4_fu_462_p2.read().range(32, 32);
        tmp_16_reg_676 = ret_V_6_fu_488_p2.read().range(32, 32);
        trunc_ln1372_2_reg_671 = trunc_ln1372_2_fu_480_p1.read();
        trunc_ln1372_3_reg_681 = trunc_ln1372_3_fu_502_p1.read();
        trunc_ln1372_4_reg_686 = trunc_ln1372_4_fu_506_p1.read();
        trunc_ln1372_reg_666 = trunc_ln1372_fu_476_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state34.read())) {
        tmp_4_reg_712 = grp_fu_179_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        tmp_8_reg_620 = grp_fu_192_p1.read();
        zext_ln87_reg_625 = zext_ln87_fu_283_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state30.read())) {
        v0_reg_701 = buf_buffer_q0.read();
        v1_reg_707 = buf_buffer_q1.read();
    }
}

void interval_normalizati::thread_add_ln339_fu_350_p2() {
    add_ln339_fu_350_p2 = (!ap_const_lv9_181.is_01() || !zext_ln339_fu_346_p1.read().is_01())? sc_lv<9>(): (sc_bigint<9>(ap_const_lv9_181) + sc_biguint<9>(zext_ln339_fu_346_p1.read()));
}

void interval_normalizati::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void interval_normalizati::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void interval_normalizati::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void interval_normalizati::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void interval_normalizati::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void interval_normalizati::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void interval_normalizati::thread_ap_CS_fsm_state25() {
    ap_CS_fsm_state25 = ap_CS_fsm.read()[24];
}

void interval_normalizati::thread_ap_CS_fsm_state26() {
    ap_CS_fsm_state26 = ap_CS_fsm.read()[25];
}

void interval_normalizati::thread_ap_CS_fsm_state27() {
    ap_CS_fsm_state27 = ap_CS_fsm.read()[26];
}

void interval_normalizati::thread_ap_CS_fsm_state28() {
    ap_CS_fsm_state28 = ap_CS_fsm.read()[27];
}

void interval_normalizati::thread_ap_CS_fsm_state29() {
    ap_CS_fsm_state29 = ap_CS_fsm.read()[28];
}

void interval_normalizati::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void interval_normalizati::thread_ap_CS_fsm_state30() {
    ap_CS_fsm_state30 = ap_CS_fsm.read()[29];
}

void interval_normalizati::thread_ap_CS_fsm_state31() {
    ap_CS_fsm_state31 = ap_CS_fsm.read()[30];
}

void interval_normalizati::thread_ap_CS_fsm_state34() {
    ap_CS_fsm_state34 = ap_CS_fsm.read()[33];
}

void interval_normalizati::thread_ap_CS_fsm_state35() {
    ap_CS_fsm_state35 = ap_CS_fsm.read()[34];
}

void interval_normalizati::thread_ap_CS_fsm_state37() {
    ap_CS_fsm_state37 = ap_CS_fsm.read()[36];
}

void interval_normalizati::thread_ap_CS_fsm_state38() {
    ap_CS_fsm_state38 = ap_CS_fsm.read()[37];
}

void interval_normalizati::thread_ap_CS_fsm_state41() {
    ap_CS_fsm_state41 = ap_CS_fsm.read()[40];
}

void interval_normalizati::thread_ap_CS_fsm_state42() {
    ap_CS_fsm_state42 = ap_CS_fsm.read()[41];
}

void interval_normalizati::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void interval_normalizati::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void interval_normalizati::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void interval_normalizati::thread_ap_block_state2() {
    ap_block_state2 = (esl_seteq<1,1,1>(tmp_nbreadreq_fu_120_p3.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, peaks_V_V_empty_n.read()));
}

void interval_normalizati::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         !(esl_seteq<1,1,1>(tmp_nbreadreq_fu_120_p3.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, peaks_V_V_empty_n.read())) && 
         esl_seteq<1,1,1>(tmp_nbreadreq_fu_120_p3.read(), ap_const_lv1_0))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void interval_normalizati::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void interval_normalizati::thread_ap_ready() {
    ap_ready = internal_ap_ready.read();
}

void interval_normalizati::thread_buf_buffer_address0() {
    buf_buffer_address0 =  (sc_lv<9>) (sext_ln544_fu_543_p1.read());
}

void interval_normalizati::thread_buf_buffer_address1() {
    buf_buffer_address1 =  (sc_lv<9>) (sext_ln544_1_fu_581_p1.read());
}

void interval_normalizati::thread_buf_buffer_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state29.read())) {
        buf_buffer_ce0 = ap_const_logic_1;
    } else {
        buf_buffer_ce0 = ap_const_logic_0;
    }
}

void interval_normalizati::thread_buf_buffer_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state29.read())) {
        buf_buffer_ce1 = ap_const_logic_1;
    } else {
        buf_buffer_ce1 = ap_const_logic_0;
    }
}

void interval_normalizati::thread_grp_fu_175_opcode() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state31.read())) {
        grp_fu_175_opcode = ap_const_lv2_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state38.read())) {
        grp_fu_175_opcode = ap_const_lv2_0;
    } else {
        grp_fu_175_opcode = "XX";
    }
}

void interval_normalizati::thread_grp_fu_175_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state38.read())) {
        grp_fu_175_p0 = v0_reg_701.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state31.read())) {
        grp_fu_175_p0 = v1_reg_707.read();
    } else {
        grp_fu_175_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void interval_normalizati::thread_grp_fu_175_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state38.read())) {
        grp_fu_175_p1 = reg_201.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state31.read())) {
        grp_fu_175_p1 = v0_reg_701.read();
    } else {
        grp_fu_175_p1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void interval_normalizati::thread_grp_fu_183_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state35.read())) {
        grp_fu_183_p0 = reg_207.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        grp_fu_183_p0 = tmp_8_reg_620.read();
    } else {
        grp_fu_183_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void interval_normalizati::thread_grp_fu_183_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state35.read())) {
        grp_fu_183_p1 = tmp_4_reg_712.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        grp_fu_183_p1 = reg_195.read();
    } else {
        grp_fu_183_p1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void interval_normalizati::thread_grp_fu_192_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state27.read())) {
        grp_fu_192_p0 = p_Val2_6_reg_649.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        grp_fu_192_p0 = zext_ln85_fu_286_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        grp_fu_192_p0 = sext_ln86_fu_279_p1.read();
    } else {
        grp_fu_192_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void interval_normalizati::thread_i_fu_297_p2() {
    i_fu_297_p2 = (!i_0_reg_164.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<8>(): (sc_biguint<8>(i_0_reg_164.read()) + sc_biguint<8>(ap_const_lv8_1));
}

void interval_normalizati::thread_icmp_ln79_fu_273_p2() {
    icmp_ln79_fu_273_p2 = (!select_ln895_fu_265_p3.read().is_01() || !ap_const_lv12_FA.is_01())? sc_lv<1>(): (sc_bigint<12>(select_ln895_fu_265_p3.read()) > sc_bigint<12>(ap_const_lv12_FA));
}

void interval_normalizati::thread_icmp_ln85_fu_291_p2() {
    icmp_ln85_fu_291_p2 = (!i_0_reg_164.read().is_01() || !ap_const_lv8_C8.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_164.read() == ap_const_lv8_C8);
}

void interval_normalizati::thread_icmp_ln895_fu_221_p2() {
    icmp_ln895_fu_221_p2 = (!peaks_V_V_dout.read().is_01() || !tmp_V_fu_112.read().is_01())? sc_lv<1>(): (sc_biguint<10>(peaks_V_V_dout.read()) > sc_biguint<10>(tmp_V_fu_112.read()));
}

void interval_normalizati::thread_idx_0_fu_450_p2() {
    idx_0_fu_450_p2 = (!zext_ln87_reg_625.read().is_01() || !p_Val2_6_reg_649.read().is_01())? sc_lv<32>(): (sc_biguint<32>(zext_ln87_reg_625.read()) + sc_biguint<32>(p_Val2_6_reg_649.read()));
}

void interval_normalizati::thread_idx_1_fu_454_p2() {
    idx_1_fu_454_p2 = (!ap_const_lv32_1.is_01() || !idx_0_reg_655.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_1) + sc_bigint<32>(idx_0_reg_655.read()));
}

void interval_normalizati::thread_internal_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         !(esl_seteq<1,1,1>(tmp_nbreadreq_fu_120_p3.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, peaks_V_V_empty_n.read())) && 
         esl_seteq<1,1,1>(tmp_nbreadreq_fu_120_p3.read(), ap_const_lv1_0))) {
        internal_ap_ready = ap_const_logic_1;
    } else {
        internal_ap_ready = ap_const_logic_0;
    }
}

void interval_normalizati::thread_interval_len_fu_259_p2() {
    interval_len_fu_259_p2 = (!sext_ln75_fu_255_p1.read().is_01() || !zext_ln75_fu_245_p1.read().is_01())? sc_lv<12>(): (sc_bigint<12>(sext_ln75_fu_255_p1.read()) + sc_biguint<12>(zext_ln75_fu_245_p1.read()));
}

void interval_normalizati::thread_isNeg_fu_356_p3() {
    isNeg_fu_356_p3 = add_ln339_fu_350_p2.read().range(8, 8);
}

void interval_normalizati::thread_lhs_V_fu_227_p1() {
    lhs_V_fu_227_p1 = esl_zext<11,10>(peaks_V_V_dout.read());
}

void interval_normalizati::thread_mantissa_V_fu_332_p4() {
    mantissa_V_fu_332_p4 = esl_concat<24,1>(esl_concat<1,23>(ap_const_lv1_1, tmp_V_8_fu_328_p1.read()), ap_const_lv1_0);
}

void interval_normalizati::thread_normalized_out_V_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state42.read())) {
        normalized_out_V_blk_n = normalized_out_V_full_n.read();
    } else {
        normalized_out_V_blk_n = ap_const_logic_1;
    }
}

void interval_normalizati::thread_normalized_out_V_din() {
    normalized_out_V_din = reg_207.read();
}

void interval_normalizati::thread_normalized_out_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state42.read()) && 
         esl_seteq<1,1,1>(normalized_out_V_full_n.read(), ap_const_logic_1))) {
        normalized_out_V_write = ap_const_logic_1;
    } else {
        normalized_out_V_write = ap_const_logic_0;
    }
}

void interval_normalizati::thread_p_Result_s_fu_310_p3() {
    p_Result_s_fu_310_p3 = p_Val2_s_fu_307_p1.read().range(31, 31);
}

void interval_normalizati::thread_p_Val2_5_fu_428_p3() {
    p_Val2_5_fu_428_p3 = (!isNeg_fu_356_p3.read()[0].is_01())? sc_lv<32>(): ((isNeg_fu_356_p3.read()[0].to_bool())? zext_ln662_fu_414_p1.read(): tmp_2_fu_418_p4.read());
}

void interval_normalizati::thread_p_Val2_6_fu_442_p3() {
    p_Val2_6_fu_442_p3 = (!p_Result_s_fu_310_p3.read()[0].is_01())? sc_lv<32>(): ((p_Result_s_fu_310_p3.read()[0].to_bool())? result_V_1_fu_436_p2.read(): p_Val2_5_fu_428_p3.read());
}

void interval_normalizati::thread_p_Val2_s_fu_307_p1() {
    p_Val2_s_fu_307_p1 = pos_reg_643.read();
}

void interval_normalizati::thread_peaks_V_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(tmp_nbreadreq_fu_120_p3.read(), ap_const_lv1_1))) {
        peaks_V_V_blk_n = peaks_V_V_empty_n.read();
    } else {
        peaks_V_V_blk_n = ap_const_logic_1;
    }
}

void interval_normalizati::thread_peaks_V_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(tmp_nbreadreq_fu_120_p3.read(), ap_const_lv1_1) && 
         !(esl_seteq<1,1,1>(tmp_nbreadreq_fu_120_p3.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, peaks_V_V_empty_n.read())))) {
        peaks_V_V_read = ap_const_logic_1;
    } else {
        peaks_V_V_read = ap_const_logic_0;
    }
}

void interval_normalizati::thread_r_V_1_fu_400_p2() {
    r_V_1_fu_400_p2 = (!zext_ln1287_fu_390_p1.read().is_01())? sc_lv<79>(): zext_ln682_fu_342_p1.read() << (unsigned short)zext_ln1287_fu_390_p1.read().to_uint();
}

void interval_normalizati::thread_r_V_fu_394_p2() {
    r_V_fu_394_p2 = (!sext_ln1311_2_fu_386_p1.read().is_01())? sc_lv<25>(): mantissa_V_fu_332_p4.read() >> (unsigned short)sext_ln1311_2_fu_386_p1.read().to_uint();
}

void interval_normalizati::thread_real_start() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_full_n.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()))) {
        real_start = ap_const_logic_0;
    } else {
        real_start = ap_start.read();
    }
}

void interval_normalizati::thread_result_V_1_fu_436_p2() {
    result_V_1_fu_436_p2 = (!ap_const_lv32_0.is_01() || !p_Val2_5_fu_428_p3.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_0) - sc_biguint<32>(p_Val2_5_fu_428_p3.read()));
}

void interval_normalizati::thread_ret_V_4_fu_462_p2() {
    ret_V_4_fu_462_p2 = (!ap_const_lv33_200.is_01() || !rhs_V_1_fu_459_p1.read().is_01())? sc_lv<33>(): (sc_biguint<33>(ap_const_lv33_200) - sc_bigint<33>(rhs_V_1_fu_459_p1.read()));
}

void interval_normalizati::thread_ret_V_5_fu_536_p3() {
    ret_V_5_fu_536_p3 = (!tmp_14_reg_661.read()[0].is_01())? sc_lv<32>(): ((tmp_14_reg_661.read()[0].to_bool())? sub_ln1372_2_fu_523_p2.read(): tmp_6_fu_529_p3.read());
}

void interval_normalizati::thread_ret_V_6_fu_488_p2() {
    ret_V_6_fu_488_p2 = (!ap_const_lv33_200.is_01() || !rhs_V_2_fu_484_p1.read().is_01())? sc_lv<33>(): (sc_biguint<33>(ap_const_lv33_200) - sc_bigint<33>(rhs_V_2_fu_484_p1.read()));
}

void interval_normalizati::thread_ret_V_7_fu_574_p3() {
    ret_V_7_fu_574_p3 = (!tmp_16_reg_676.read()[0].is_01())? sc_lv<32>(): ((tmp_16_reg_676.read()[0].to_bool())? sub_ln1372_4_fu_561_p2.read(): tmp_7_fu_567_p3.read());
}

void interval_normalizati::thread_ret_V_fu_235_p2() {
    ret_V_fu_235_p2 = (!lhs_V_fu_227_p1.read().is_01() || !rhs_V_fu_231_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(lhs_V_fu_227_p1.read()) - sc_biguint<11>(rhs_V_fu_231_p1.read()));
}

void interval_normalizati::thread_rhs_V_1_fu_459_p1() {
    rhs_V_1_fu_459_p1 = esl_sext<33,32>(idx_0_reg_655.read());
}

void interval_normalizati::thread_rhs_V_2_fu_484_p1() {
    rhs_V_2_fu_484_p1 = esl_sext<33,32>(idx_1_fu_454_p2.read());
}

void interval_normalizati::thread_rhs_V_fu_231_p1() {
    rhs_V_fu_231_p1 = esl_zext<11,10>(tmp_V_fu_112.read());
}

void interval_normalizati::thread_select_ln895_fu_265_p3() {
    select_ln895_fu_265_p3 = (!icmp_ln895_fu_221_p2.read()[0].is_01())? sc_lv<12>(): ((icmp_ln895_fu_221_p2.read()[0].to_bool())? sext_ln71_fu_241_p1.read(): interval_len_fu_259_p2.read());
}

void interval_normalizati::thread_sext_ln1311_1_fu_382_p1() {
    sext_ln1311_1_fu_382_p1 = esl_sext<32,9>(ush_fu_374_p3.read());
}

void interval_normalizati::thread_sext_ln1311_2_fu_386_p1() {
    sext_ln1311_2_fu_386_p1 = esl_sext<25,9>(ush_fu_374_p3.read());
}

void interval_normalizati::thread_sext_ln1311_fu_370_p1() {
    sext_ln1311_fu_370_p1 = esl_sext<9,8>(sub_ln1311_fu_364_p2.read());
}

void interval_normalizati::thread_sext_ln544_1_fu_581_p1() {
    sext_ln544_1_fu_581_p1 = esl_sext<64,32>(ret_V_7_fu_574_p3.read());
}

void interval_normalizati::thread_sext_ln544_fu_543_p1() {
    sext_ln544_fu_543_p1 = esl_sext<64,32>(ret_V_5_fu_536_p3.read());
}

void interval_normalizati::thread_sext_ln71_fu_241_p1() {
    sext_ln71_fu_241_p1 = esl_sext<12,11>(ret_V_fu_235_p2.read());
}

void interval_normalizati::thread_sext_ln75_fu_255_p1() {
    sext_ln75_fu_255_p1 = esl_sext<12,11>(sub_ln75_fu_249_p2.read());
}

void interval_normalizati::thread_sext_ln86_fu_279_p1() {
    sext_ln86_fu_279_p1 = esl_sext<32,12>(select_ln895_reg_606.read());
}

void interval_normalizati::thread_start_out() {
    start_out = real_start.read();
}

void interval_normalizati::thread_start_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()))) {
        start_write = ap_const_logic_1;
    } else {
        start_write = ap_const_logic_0;
    }
}

void interval_normalizati::thread_sub_ln1311_fu_364_p2() {
    sub_ln1311_fu_364_p2 = (!ap_const_lv8_7F.is_01() || !tmp_V_7_fu_318_p4.read().is_01())? sc_lv<8>(): (sc_biguint<8>(ap_const_lv8_7F) - sc_biguint<8>(tmp_V_7_fu_318_p4.read()));
}

void interval_normalizati::thread_sub_ln1372_2_fu_523_p2() {
    sub_ln1372_2_fu_523_p2 = (!ap_const_lv32_0.is_01() || !tmp_15_fu_515_p3.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_0) - sc_biguint<32>(tmp_15_fu_515_p3.read()));
}

void interval_normalizati::thread_sub_ln1372_3_fu_548_p2() {
    sub_ln1372_3_fu_548_p2 = (!ap_const_lv9_0.is_01() || !trunc_ln1372_4_reg_686.read().is_01())? sc_lv<9>(): (sc_biguint<9>(ap_const_lv9_0) - sc_biguint<9>(trunc_ln1372_4_reg_686.read()));
}

void interval_normalizati::thread_sub_ln1372_4_fu_561_p2() {
    sub_ln1372_4_fu_561_p2 = (!ap_const_lv32_0.is_01() || !tmp_17_fu_553_p3.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_0) - sc_biguint<32>(tmp_17_fu_553_p3.read()));
}

void interval_normalizati::thread_sub_ln1372_fu_510_p2() {
    sub_ln1372_fu_510_p2 = (!ap_const_lv9_0.is_01() || !trunc_ln1372_2_reg_671.read().is_01())? sc_lv<9>(): (sc_biguint<9>(ap_const_lv9_0) - sc_biguint<9>(trunc_ln1372_2_reg_671.read()));
}

void interval_normalizati::thread_sub_ln75_fu_249_p2() {
    sub_ln75_fu_249_p2 = (!ap_const_lv11_200.is_01() || !rhs_V_fu_231_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(ap_const_lv11_200) - sc_biguint<11>(rhs_V_fu_231_p1.read()));
}

void interval_normalizati::thread_tmp_13_fu_406_p3() {
    tmp_13_fu_406_p3 = r_V_fu_394_p2.read().range(24, 24);
}

void interval_normalizati::thread_tmp_15_fu_515_p3() {
    tmp_15_fu_515_p3 = esl_concat<23,9>(ap_const_lv23_0, sub_ln1372_fu_510_p2.read());
}

void interval_normalizati::thread_tmp_17_fu_553_p3() {
    tmp_17_fu_553_p3 = esl_concat<23,9>(ap_const_lv23_0, sub_ln1372_3_fu_548_p2.read());
}

void interval_normalizati::thread_tmp_2_fu_418_p4() {
    tmp_2_fu_418_p4 = r_V_1_fu_400_p2.read().range(55, 24);
}

void interval_normalizati::thread_tmp_6_fu_529_p3() {
    tmp_6_fu_529_p3 = esl_concat<23,9>(ap_const_lv23_0, trunc_ln1372_reg_666.read());
}

void interval_normalizati::thread_tmp_7_fu_567_p3() {
    tmp_7_fu_567_p3 = esl_concat<23,9>(ap_const_lv23_0, trunc_ln1372_3_reg_681.read());
}

void interval_normalizati::thread_tmp_V_7_fu_318_p4() {
    tmp_V_7_fu_318_p4 = p_Val2_s_fu_307_p1.read().range(30, 23);
}

void interval_normalizati::thread_tmp_V_8_fu_328_p1() {
    tmp_V_8_fu_328_p1 = p_Val2_s_fu_307_p1.read().range(23-1, 0);
}

void interval_normalizati::thread_tmp_nbreadreq_fu_120_p3() {
    tmp_nbreadreq_fu_120_p3 =  (sc_lv<1>) ((peaks_V_V_empty_n.read()));
}

void interval_normalizati::thread_trunc_ln1372_2_fu_480_p1() {
    trunc_ln1372_2_fu_480_p1 = ret_V_4_fu_462_p2.read().range(9-1, 0);
}

void interval_normalizati::thread_trunc_ln1372_3_fu_502_p1() {
    trunc_ln1372_3_fu_502_p1 = ret_V_6_fu_488_p2.read().range(9-1, 0);
}

void interval_normalizati::thread_trunc_ln1372_4_fu_506_p1() {
    trunc_ln1372_4_fu_506_p1 = ret_V_6_fu_488_p2.read().range(9-1, 0);
}

void interval_normalizati::thread_trunc_ln1372_fu_476_p1() {
    trunc_ln1372_fu_476_p1 = ret_V_4_fu_462_p2.read().range(9-1, 0);
}

void interval_normalizati::thread_ush_fu_374_p3() {
    ush_fu_374_p3 = (!isNeg_fu_356_p3.read()[0].is_01())? sc_lv<9>(): ((isNeg_fu_356_p3.read()[0].to_bool())? sext_ln1311_fu_370_p1.read(): add_ln339_fu_350_p2.read());
}

void interval_normalizati::thread_zext_ln1287_fu_390_p1() {
    zext_ln1287_fu_390_p1 = esl_zext<79,32>(sext_ln1311_1_fu_382_p1.read());
}

void interval_normalizati::thread_zext_ln339_fu_346_p1() {
    zext_ln339_fu_346_p1 = esl_zext<9,8>(tmp_V_7_fu_318_p4.read());
}

void interval_normalizati::thread_zext_ln662_fu_414_p1() {
    zext_ln662_fu_414_p1 = esl_zext<32,1>(tmp_13_fu_406_p3.read());
}

void interval_normalizati::thread_zext_ln682_fu_342_p1() {
    zext_ln682_fu_342_p1 = esl_zext<79,25>(mantissa_V_fu_332_p4.read());
}

void interval_normalizati::thread_zext_ln75_fu_245_p1() {
    zext_ln75_fu_245_p1 = esl_zext<12,10>(peaks_V_V_dout.read());
}

void interval_normalizati::thread_zext_ln85_fu_286_p1() {
    zext_ln85_fu_286_p1 = esl_zext<32,8>(i_0_reg_164.read());
}

void interval_normalizati::thread_zext_ln87_fu_283_p1() {
    zext_ln87_fu_283_p1 = esl_zext<32,10>(tmp_V_load_reg_596.read());
}

void interval_normalizati::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && !(esl_seteq<1,1,1>(tmp_nbreadreq_fu_120_p3.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, peaks_V_V_empty_n.read())) && esl_seteq<1,1,1>(tmp_nbreadreq_fu_120_p3.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(tmp_nbreadreq_fu_120_p3.read(), ap_const_lv1_1) && !(esl_seteq<1,1,1>(tmp_nbreadreq_fu_120_p3.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, peaks_V_V_empty_n.read())) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln79_fu_273_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(tmp_nbreadreq_fu_120_p3.read(), ap_const_lv1_1) && !(esl_seteq<1,1,1>(tmp_nbreadreq_fu_120_p3.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, peaks_V_V_empty_n.read())) && esl_seteq<1,1,1>(icmp_ln79_fu_273_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && (esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln85_fu_291_p2.read()) || 
  esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln79_reg_611.read())))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state20;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_fsm_state21;
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_fsm_state22;
            break;
        case 2097152 : 
            ap_NS_fsm = ap_ST_fsm_state23;
            break;
        case 4194304 : 
            ap_NS_fsm = ap_ST_fsm_state24;
            break;
        case 8388608 : 
            ap_NS_fsm = ap_ST_fsm_state25;
            break;
        case 16777216 : 
            ap_NS_fsm = ap_ST_fsm_state26;
            break;
        case 33554432 : 
            ap_NS_fsm = ap_ST_fsm_state27;
            break;
        case 67108864 : 
            ap_NS_fsm = ap_ST_fsm_state28;
            break;
        case 134217728 : 
            ap_NS_fsm = ap_ST_fsm_state29;
            break;
        case 268435456 : 
            ap_NS_fsm = ap_ST_fsm_state30;
            break;
        case 536870912 : 
            ap_NS_fsm = ap_ST_fsm_state31;
            break;
        case 1073741824 : 
            ap_NS_fsm = ap_ST_fsm_state32;
            break;
        case 2147483648 : 
            ap_NS_fsm = ap_ST_fsm_state33;
            break;
        case 4294967296 : 
            ap_NS_fsm = ap_ST_fsm_state34;
            break;
        case 8589934592 : 
            ap_NS_fsm = ap_ST_fsm_state35;
            break;
        case 17179869184 : 
            ap_NS_fsm = ap_ST_fsm_state36;
            break;
        case 34359738368 : 
            ap_NS_fsm = ap_ST_fsm_state37;
            break;
        case 68719476736 : 
            ap_NS_fsm = ap_ST_fsm_state38;
            break;
        case 137438953472 : 
            ap_NS_fsm = ap_ST_fsm_state39;
            break;
        case 274877906944 : 
            ap_NS_fsm = ap_ST_fsm_state40;
            break;
        case 549755813888 : 
            ap_NS_fsm = ap_ST_fsm_state41;
            break;
        case 1099511627776 : 
            ap_NS_fsm = ap_ST_fsm_state42;
            break;
        case 2199023255552 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state42.read()) && esl_seteq<1,1,1>(normalized_out_V_full_n.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else {
                ap_NS_fsm = ap_ST_fsm_state42;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<42>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

}

